### ISSUE TITLE
How does it compare to other json schema validators?

### ISSUE THREAD

**Issue by simon-p-r** [christkv/vitesse#2]
Hi

I saw your benchmarks, how does it compare to other json schema validator libraries?  I think a comparison with joi is difficult as that is a dsl whereas this library is designed to enable developers to build their own dsl.  I use z-schema which allows async custom formats at field level.  Is this something that is planned for Vitesse in the future? 

Thanks

**Comment by christkv** [comment]
It does pretty decent. There are still tons of opportunities to optimize the built in vitesse generation library and that will be a goal going forward (once I have some free cycles). The closure compiler generates code that is comparable to the fastest ones out there.

The son schema validator was written to prove the correctness of the vitesse validation framework. The idea being that anything basing themselves of vitesse will gain all improvements over time.

**Comment by christkv** [comment]
One of the goals of this is to be a building block for out next ES6 ODM prototype allowing the amount of time spent in js to be as low as possible, increasing the total concurrency in node.js for a single process.

**Comment by simon-p-r** [comment]
Ok thanks for your feedback, I will watch this space. What is the name of new orm called?

**Comment by christkv** [comment]
for now monogram but might be renamed mongoose next gen or something to allow people to find it
